name: Deploy to VPS (docker-compose v1)

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-vps
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy repo to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/my-ecommerce"
          rm: true
          overwrite: true
          exclude: |
            .git
            node_modules
            tmp
            log

      - name: Deploy via SSH (docker-compose v1)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euo pipefail
            cd ~/my-ecommerce

            # Ensure docker-compose v1 exists (install if missing)
            if ! command -v docker-compose >/dev/null 2>&1; then
              echo "Installing docker-compose v1..."
              VERSION="1.29.2"
              sudo curl -L "https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose version
            fi

            # Show effective config (quick sanity check)
            docker-compose config -q

            # Recreate stack
            docker-compose down || true
            docker-compose up -d --build --remove-orphans

            # Clean dangling images
            docker image prune -f || true
